version: "3"

services:
  postgres-printgo:
    image: postgres:alpine
    container_name: postgres-printgo
    ports:
      - "5432:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=printgo-local
    networks:
      - printgo_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "printgo@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "printgo123!"
    ports:
      - "16544:80"
    depends_on:
      - postgres-printgo
    networks:
      - printgo_network

networks:
  printgo_network:
    name: printgo_network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"