name: Prisma CI/CD Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Prisma push
      run: npx prisma db push --skip-generate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - name: Prisma Migrate Deploy
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
