name: Prisma CI/CD Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Remove local prisma
      run: rm -rf prisma
    
    - name: make cockroach-prisma become prisma
      run: mv cockroach-prisma prisma

    - name: Install Dependencies
      run: npm install

    - name: Prisma Migrate Deploy
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
