name: Prisma CI/CD Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Prisma Migrate Deploy && Prisma push
      run: npx prisma migrate deploy && npx prisma db push
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_DEV }}
